version: '3'
services:
  testpyapp:
    image: testpyapp
    ports:
      - 8990:8080
    environment:
      DB_HOST: postgres
      DB_PASS: password
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

